import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from 'next/script';
import Nav from '@/components/nav';
import Footer from '@/components/footer';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="leading-normal tracking-normal text-white gradient">
        <Nav />
        {children}
        <Footer />
        <Script src="/footer.js" />
      </body>
    </html>
  );
}
